### ISSUE TITLE
Make the generated URLs shorter

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-urlshortener#12]
Right now the generated URLs are of the following form `http://localhost:8080/xwiki/rest/p/{pageID}`. The idea of this issue is to remove the `rest` part, making the URLs as `http://localhost:8080/xwiki/p/{pageID}`.

Then all new links (links copied using the `Get shortened URL` button)  will be of this form.
Note that any link copied previously to this implementation will continue to work as expected, to not break backwards compatibility. 

This needs to be done by using https://extensions.xwiki.org/xwiki/bin/view/Extension/Resource%20API#HAddinganewResourceTypeHandler

**Comment by vmassol** [comment]
Note that it's not just about making it shorter, it's also about making it more logical. Using a REST action for something that doesn't produce REST is weird and incorrect (REST is for machines and a REST endpoint is not supposed to produce rendered HTML for humans).

**Comment by vmassol** [comment]
BTW what does `p` stand for? :)

**Comment by oanalavinia** [comment]
`p` stands for `page` :)
