### ISSUE TITLE
Documentation - explain how 5 digits unique code is created

### ISSUE THREAD

**Issue by lamblinc** [xwikisas/application-urlshortener#4]
In documentation, Code.URLShortenerClass should be explained (how the hexadecimal 5 digit code is created).

**Comment by oanalavinia** [comment]
Hi @lamblinc! I added some documentation details on https://store.xwiki.com/xwiki/bin/view/Extension/URL%20Shortener%20Application%20(Pro)/#documentation
Can you let me know if this is what you expected?

**Comment by lamblinc** [comment]
Thanks, it seems so for the change, for the ID generator itself, is it some sort of randomizer or is it incremental ? I'll let you know if I have other feedbacks.

**Comment by oanalavinia** [comment]
Yes, the ID is randomly generated
