### ISSUE TITLE
Translate application in french

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-urlshortener#6]
Related to https://github.com/xwikisas/application-urlshortener/issues/3

**Comment by oanalavinia** [comment]
Hi, @lamblinc !
Could you please help me with the french translation? There are only 3 keys, but since I know very little french, I might be  far away from the right formulation:) (I just used translate)

```
urlshortener.menu.button.title=Obtenir une URL raccourcie
urlshortener.menu.action.done=URL copiée dans le presse-papiers
urlshortener.menu.action.fail=Une erreur s'est produite lors de la création de l'URL raccourcie.
```

**Comment by lamblinc** [comment]
> Hi, @lamblinc ! Could you please help me with the french translation? There are only 3 keys, but since I know very little french, I might be far away from the right formulation:) (I just used translate)
> 
> ```
> urlshortener.menu.button.title=Obtenir une URL raccourcie
> urlshortener.menu.action.done=URL copiée dans le presse-papiers
> urlshortener.menu.action.fail=Une erreur s'est produite lors de la création de l'URL raccourcie.
> ```

These translations seem OK, thanks !
