### ISSUE TITLE
When creating a shortened url, we should allow notifications for this event to be deactivated

### ISSUE THREAD

**Issue by lamblinc** [xwikisas/application-urlshortener#9]
When creating the shortened url, a new version of the page is created, thus a notification is sent.

These notifications may be useless (or at least some may want to get rid of it if necessary), so it would be a nice feature to create a setting to disable these notifications.

Another way to avoid notifications would be not to create a new version of the page.

**Comment by oanalavinia** [comment]
Now we don't add any history entry when the shortened URL is first created, since this is just technical info. This will  disable the notification
